### ISSUE TITLE
Elasticsearch health check failed

### ISSUE THREAD

**Issue by choi-hye-min** [choi-hye-min/design-names#2]
ES 클러스터에 사용되는 9300 port 문제 인거 같아요
local로 클러스터 구성해서 테스트 했을때는 정상적으로 잘되는거 확인함

`2019-05-03 01:02:03.481  WARN 85551 --- [on(7)-127.0.0.1] o.s.b.a.e.ElasticsearchHealthIndicator   : Elasticsearch health check failed

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{nbtN4vhDTJK6aNt1OI4dQw}{http://home.devtopia.net}{185.199.108.153:9200}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:349) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:247) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:381) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:708) ~[elasticsearch-6.4.3.jar:6.4.3]`

**Comment by choi-hye-min** [comment]
Success!
